USER root

WORKDIR /tmp

RUN apt install -y wget zlib1g-dev:i386

RUN wget https://ppa.launchpadcontent.net/linuxuprising/libpng12/ubuntu/pool/main/libp/libpng/libpng_1.2.54.orig.tar.xz
RUN tar Jxfv libpng_1.2.54.orig.tar.xz
WORKDIR /tmp/libpng-1.2.54
RUN CFLAGS="-m32 -O1 -W -Wall -pedantic -std=c99" LDFLAGS="-m32" ./configure
RUN CFLAGS="-m32 -O1 -W -Wall -pedantic -std=c99" LDFLAGS="-m32" make
RUN make install
RUN ln -s /usr/local/lib/libpng12.so.0.54.0 /usr/lib/libpng12.so
RUN ln -s /usr/local/lib/libpng12.so.0.54.0 /usr/lib/libpng12.so.0

USER project

WORKDIR /project

ENTRYPOINT /bin/bash
